language: python
python:
- '3.6'
- '3.7'
install:
- pip install -r requirements.txt
script:
- python -m pytest tests/
deploy:
  provider: heroku
  api_key:
    secure: b3WmSqsNvcNjOczghK4uOKPOWREPnmvmXy9NU0VI7x9b0Tpxm3e4joIy+aBPXvrFvBfw33rhnv6YneszkFaqk7Z07n5fo5jIL0LXPL6v/vGAgFqPWV0psTYK8bdA/L+ty8KMDqCVZXj9Fd16i0PgXZuwUGoXWTD8ab9jW7MnUy5+Bz6VOGeAkS1f0EN49coagE5y/kSHL39JjBFfAHzDxFvtNdgmt4HosYRCObVQK9SHv+4Wsd/YszJKp2ppo5hl55M09e79OHZIv1U9Ev/O9NQ6QYeXTgwErOP5PPpS2X1w4qoBWlH5M2hT6+t02yrMP1awqzolzhdZW2Q0AXKs01z8reTJkym9aPtZtkYT7VULY3Egq23iXE7P9mPxB5yUG5caJvtfzhYjngJFMI8XhRKcLJuChSEKAXd6FggnNh5BTVEbaoHv6X+A6l5WQ7KQhYgfh8ep3TooHNY31tO3/9EdIwRZ31xDa3rSq5T158NEcbfBVV/f+AlsCiKtKlaB/wUO8Jq99oohhieXheoi8iyY5TkT4OjleSa9BOEhhzkR34gvmiKeCrtNKktSnuzLFgjftp4YnirbjsWJT25GCnfvWZGLht3SL+ARCbyqwN5jhMSv3Dmdg+JvggSyonRXJFPhl0BTk0v9++bOFlD0zZKiNo4DrkpxYqnvTPR9YVA=
  app: csc-478-travel-api
  on:
    repo: yourFriendWes/csc-478-cap
