language: python
python:
- '3.6'
- '3.7'
install:
- pip install -r requirements.txt
script:
- python -m pytest tests/
deploy:
  provider: heroku
  api_key:
    secure: b3WmSqsNvcNjOczghK4uOKPOWREPnmvmXy9NU0VI7x9b0Tpxm3e4joIy+aBPXvrFvBfw33rhnv6YneszkFaqk7Z07n5fo5jIL0LXPL6v/vGAgFqPWV0psTYK8bdA/L+ty8KMDqCVZXj9Fd16i0PgXZuwUGoXWTD8ab9jW7MnUy5+Bz6VOGeAkS1f0EN49coagE5y/kSHL39JjBFfAHzDxFvtNdgmt4HosYRCObVQK9SHv+4Wsd/YszJKp2ppo5hl55M09e79OHZIv1U9Ev/O9NQ6QYeXTgwErOP5PPpS2X1w4qoBWlH5M2hT6+t02yrMP1awqzolzhdZW2Q0AXKs01z8reTJkym9aPtZtkYT7VULY3Egq23iXE7P9mPxB5yUG5caJvtfzhYjngJFMI8XhRKcLJuChSEKAXd6FggnNh5BTVEbaoHv6X+A6l5WQ7KQhYgfh8ep3TooHNY31tO3/9EdIwRZ31xDa3rSq5T158NEcbfBVV/f+AlsCiKtKlaB/wUO8Jq99oohhieXheoi8iyY5TkT4OjleSa9BOEhhzkR34gvmiKeCrtNKktSnuzLFgjftp4YnirbjsWJT25GCnfvWZGLht3SL+ARCbyqwN5jhMSv3Dmdg+JvggSyonRXJFPhl0BTk0v9++bOFlD0zZKiNo4DrkpxYqnvTPR9YVA=
  app: csc-478-travel-api
  on:
    repo: yourFriendWes/csc-478-cap
env:
  global:
    secure: vRS8KWSL8G2f/gmQh2iqcmc+ooUVJDwiZFdDWmH1Vs09l1KvuYkK6yOD4qvzDz2wGL7gOWoKJ1sJFcO4whQgYKI1o6d5VakW80X+DfYq0qjjmG6hWPuCWJg+eoOTe0q/87KiNrtDWrLtKx/rWPjqPF1xUAUyXAkax3CatvcHOHLOuEVW79ebakbsHpMMmLwBiO6TcYTA2JvPecv1JVjoC+nyLkGTrEsdTnpKL6QgYZ0/Sny8ckAD42kvTXVoJCpuVPjFOg6XwkvnMkWb63gJMDDgyrJomQAo4mcaiZpOVrJr3Y6bHLNn4VJWVg2NmZI0dTLjBvDew9/UuCfTwWpHhuCKUwM5RNkP0tj6XdgIdkIv/UYlN2whRpyNXY6RMdGlmzV6mEqVo3ZA4PEoYzGmGh/TdYM2rjfJqY7TPS3afY1EDidjIQGLE8Xxu9iivXAOy8+5xMREz+/pwMpzCjplaDmBZYecgs4RM2zAZZSxb+XvElZsMjUBFJWtynUetVVl7QbGsmDJa4Y4GM+WdNSKNcWTpDpactBym91aTtrYmv4dSpv4OnpQgTX99n9UrkBFjqiNNferlRfjz62XppDeXEhKCFweDThJzMytozpZyQX1IcvCm7x7mQMo6uxP+0A8hitHQNgXYXxTOWUnP6k5lY3XbyuyY+YychegfqXXY3k=
