swagger: "2.0"
info:
  description: This is the capstone project for group 8
  version: "0.0.1"
  title: Traveler API
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the run application
paths:
  /location:
    get:
      operationId: "api.location.supported_locations"
      tags:
        - "Location"
      summary: "The location data structure supported by the traveler application"
      description: "Returns list of supported locations"
      responses:
        200:
          description: "Successful request for supported locations"
          schema:
            type: "array"
            items:
              properties:
                country:
                  type: "string"
